server:
  port: 80
camunda.bpm:
  job-execution:
    enabled: true
awsParameterStorePropertySource:
  enabled: true
awsParameterStoreSource:
  multiRegion:
    ssmClient:
      regions: ${AWS_DEFAULT_REGION}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    jwk-uri: https://cognito-idp.${AWS_DEFAULT_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}
management:
  endpoints:
    web:
      exposure:
        include: env,health,metrics
dd:
  statsd:
    agent:
      port: 8125
      prefix: "statsd"
