name: "Terraform"
on: [pull_request]

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    container:
      image: alpine/terragrunt:0.12.29
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform linter
        id: fmt
        run: terraform fmt -check -recursive

      # - name: Update pull request
      #   uses: actions/github-script@0.9.0
      #   if: github.event_name == 'pull_request'
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
      #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
              
      #       github.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: output
      #       })
