name: "Terraform"
on: [pull_request]

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    container:
      image: alpine/terragrunt:0.12.29
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform linter
        id: fmt
        run: terraform fmt -check -recursive
